version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-net

  database:
    image: postgres:13
    container_name: postgres-database # Host name/address to use for DBMS server connection
    env_file:
      - ./database/.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-DBMS
    environment:
      PGADMIN_DEFAULT_EMAIL: ct@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # Access DBMS at http://localhost:8080 using the credentials above
    depends_on:
      - database
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - app-net

  admin-backend:
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    container_name: admin-backend
    ports:
      - "6000:6000"
    depends_on:
      - database
    env_file:
      - ./admin-backend/.env
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
